<template>
  <div class="animate__animated animate__fadeIn">
    <BlogHeader />
    <main>
		
		<!-- /page_header -->

		<div class="container margin_30_20">			
			<div class="main_title center">
				<span><em></em></span>
				<h2>Privacy Policy</h2>
				<!-- <p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p> -->
			</div>

			<div class="row justify-content-center align-items-center add_bottom_15">
				<div class="col-lg-8 col-offset-lg-1">
					<div class="box_about">
						<!-- <h3 style="font-size: 150%;">Terms of Service</h3> -->
						<p class="center-sm" style="font-weight: 500;">
                            Last updated: April 22, 2020
<br>
This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
<br>
We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                        </p>
						<!-- <img :src="require('~/assets/img/arrow_aout.png')" alt="" class="arrow_1"> -->
						<h3 style="font-size: 170%;">Interpretation and Definitions</h3>
                        <h3 style="font-size: 150%;">Interpretation</h3>
                            <p class="justify-sm">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                            </p>
                        <h3 style="font-size: 150%;">Definitions</h3>
                        <p class="justify-sm">
                            For the purposes of this Privacy Policy:
                            <ul style="list-style: disc;">
                                <li>
                                    Account means a unique account created for You to access our Service or parts of our Service.
                                </li>
                                <li>
                                    Company (referred to as either "Chops", "We", "Us" or "Our" in this Agreement) refers to Chops Limited, St. James House, Ademola Adetokunbo Crescent, Wuse 2, Abuja.
                                </li>
                                <li>
                                    Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
                                </li>
                                <li>
                                    Country refers to: Nigeria
                                </li>
                                <li>
                                    Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
                                </li>
                                <li>
                                    Personal Data is any information that relates to an identified or identifiable individual.
                                </li>
                                <li>
                                    Service refers to the Website.
                                </li>
                                <li>
                                    Service Provider means any natural or legal person who processes the data on behalf of Chops. It refers to third-party companies or individuals employed by Chops to facilitate the Service, to provide the Service on behalf of Chops, to perform services related to the Service or to assist Chops in analyzing how the Service is used.
                                </li>
                                <li>
                                    Third-party Social Media Service refers to any website or any social network website through which a User can log in or create an account to use the Service.
                                </li>
                                <li>
                                    Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                                </li>
                                <li>
                                    Website refers to Chops, accessible from https://Chops.com
                                </li>
                                <li>
                                    You means the individual accessing or using the Service, or Chops, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
                                </li>
                            </ul>
                        </p>
                        <h3 style="font-size: 170%;">Collecting and Using Your Personal Data</h3>
                        <h3 style="font-size: 170%;">Types of Data Collected</h3>
                        <h3 style="font-size: 150%;">Personal Data</h3>
                        <p class="justify-sm">
                            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                            <ul style="list-style: disc;">
                                <li>Email address</li>
                                <li>First name and last name</li>
                                <li>Phone number</li>
                                <li>Usage Data</li>
                            </ul>
                        </p>

                        <h3 style="font-size: 150%;">Usage Data</h3>
                        <p class="justify-sm">Usage Data is collected automatically when using the Service.</p>
                        <p class="justify-sm">Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                        <p class="justify-sm">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
                        <p class="justify-sm">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

                        <h3 style="font-size: 150%;">Tracking Technologies and Cookies</h3>
                        <p class="justify-sm">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
                        <p class="justify-sm">You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</p>
                        <p class="justify-sm">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser. Learn more about cookies: All About Cookies.</p>
                        <p class="justify-sm">We use both session and persistent Cookies for the purposes set out below:
                            <ul style="list-style: disc;">
                                <li>
                                    <p class="justify-sm">
                                        Necessary / Essential Cookies <br>
                                        Type: Session Cookies <br>
                                        Administered by: Us <br>
                                        Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
                                    </p>
                                </li>
                                <li>
                                    <p class="justify-sm">
                                        Cookies Policy / Notice Acceptance Cookies <br>
                                        Type: Persistent Cookies <br>
                                        Administered by: Us <br>
                                        Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
                                    </p>
                                </li>
                                <li>
                                    <p class="justify-sm">
                                        Functionality Cookies<br>
                                        Type: Persistent Cookies<br>
                                        Administered by: Us<br>
                                        Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
                                    </p>
                                </li>
                            </ul>
                        </p>
                        <h3 style="font-size: 170%;">Use of Your Personal Data</h3>
                        <p class="justify-sm">We may use Personal Data for the following purposes:</p>
                        <ul style="list-style: disc;">
                            <li>
                                <p class="justify-sm">
                                    To provide and maintain our Service, including to monitor the usage of our Service.    
                                </p>
                            </li>
                            <li>
                                <p class="justify-sm">
                                    To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.
                                </p>
                            </li>
                            <li>
                                <p class="justify-sm">
                                    For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.
                                </p>
                            </li>
                            <li>
                                <p class="justify-sm">
                                    To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
                                </p>
                            </li>
                            <li>
                                <p class="justify-sm">
                                    To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
                                </p>
                            </li>
                            <li>
                                <p class="justify-sm">
                                    To manage Your requests: To attend and manage Your requests to Us.
                                </p>
                            </li>
                            We may share your personal information in the following situations:
                            <li>
                                <p class="justify-sm">
                                    With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.
                                </p>
                            </li>
                            <li>
                                <p class="justify-sm">
                                    For Business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.
                                </p>
                            </li>
                            <li>
                                <p class="justify-sm">
                                    With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.
                                </p>
                            </li>
                            <li>
                                <p class="justify-sm">
                                    With Business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.
                                </p>
                            </li>
                            <li>
                                <p class="justify-sm">
                                    With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.
                                </p>
                            </li>
                        </ul>

                        <h3 style="font-size: 170%;">Retention of Your Personal Data</h3>
                        <p class="justify-sm">
                            Chops will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                        </p>
                        <p class="justify-sm">
                            Chops will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
                        </p>

                        <h3 style="font-size: 170%;">Transfer of Your Personal Data</h3>
                        <p class="justify-sm">
                            Your information, including Personal Data, is processed at Chops' operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
                        </p>
                        <p class="justify-sm">
                            Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
                        </p>
                        <p class="justify-sm">
                            Chops will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
                        </p>

                        <h3 style="font-size: 170%;">Disclosure of Your Personal Data</h3>
                        <h3 style="font-size: 150%;">Business Transactions</h3>
                        <p class="justify-sm">
                            If Chops is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
                        </p>

                        <h3 style="font-size: 150%;">Law enforcement</h3>
                        <p class="justify-sm">
                            Under certain circumstances, Chops may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
                        </p>

                        <h3 style="font-size: 150%;">Other legal requirements</h3>
                        <p class="justify-sm">
                           Chops may disclose Your Personal Data in the good faith belief that such action is necessary to:
                           <ul style="list-style: disc;">
                                <li>Comply with a legal obligation</li>
                                <li>Protect and defend the rights or property of Chops</li>
                                <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                                <li>Protect the personal safety of Users of the Service or the public</li>
                                <li>Protect against legal liability</li>
                            </ul>
                        </p>

                        <h3 style="font-size: 170%;">Security of Your Personal Data</h3>
                        <p class="justify-sm">
                           The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                        </p>

                        <h3 style="font-size: 170%;">Links to Other Websites</h3>
                        <p class="justify-sm">
                           Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
                        </p>
                        <p class="justify-sm">
                           We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                        </p>

                        <h3 style="font-size: 170%;">Third Party</h3>
                        <p class="justify-sm">
                           We make use of the following third party services.
                           <ul style="list-style: disc;">
                                <li>Google Maps API for Geolocation and Mapping services. You can find Google's Privacy Policy here</li>
                                <li>Sign In with Google. You can find Google's Privacy Policy here</li>
                                <li>Sign In with Facebook. You can find Facebook’s Privacy Policy here</li>
                                <li>Sign In with Twitter. You can find Twitter’s Privacy Policy here</li>
                                <li>Paystack for Payment Processing. You can find Paystack’s Terms &amp; Police here</li>
                            </ul>
                        </p>

                        <h3 style="font-size: 170%;">Changes to this Privacy Policy</h3>
                        <p class="justify-sm">
                           We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                        </p>
                        <p class="justify-sm">
                           We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
                        </p>
                        <p class="justify-sm">
                           You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                        </p>

                        <h3 style="font-size: 170%;">Contact Us</h3>
                        <p class="justify-sm">
                           If you have any questions about this Privacy Policy, You can contact us:
                           <ul style="list-style: disc;">
                                <li>By email: <a href="mailto:hello@chops.ng">hello@chops.ng</a></li>
                                <li>On the website: <a href="https://food.chops.ng/support">food.chops.ng/support</a></li>
                            </ul>
                        </p>
					</div>
				</div>
			</div>
		</div>
	<!-- /container -->
		
	</main>
    <Footer />
    <Addons />
  </div>
</template>

<script>
import axios from '@nuxtjs/axios'
export default {
  mounted() {

    let common_join_js = document.createElement('script')
    common_join_js.setAttribute('src', `/js/common_join.js`)
    document.body.appendChild(common_join_js)

    let script3 = document.createElement('script')
    script3.setAttribute('src', `/js/validate.js`)
    document.body.appendChild(script3)

    let script4 = document.createElement('script')
    script4.setAttribute('src', `/js/jarallax.min.js`)
    document.body.appendChild(script4)

    let script5 = document.createElement('script')
    script5.setAttribute('src', `/js/jarallax-video.min.js`)
    document.body.appendChild(script5)

    function initMap() {
      var input = document.getElementById('autocomplete');
      var autocomplete = new google.maps.places.Autocomplete(input);

      autocomplete.addListener('place_changed', function() {
        var place = autocomplete.getPlace();
          if (!place.geometry) {
              window.alert("Autocomplete's returned place contains no geometry");
              return;
          }

          var address = '';
          if (place.address_components) {
              address = [
                (place.address_components[0] && place.address_components[0].short_name || ''),
                  (place.address_components[1] && place.address_components[1].short_name || ''),
                  (place.address_components[2] && place.address_components[2].short_name || '')
              ].join(' ');
          }
      });
    }
  }
}
</script>
<style>
	ol {
		padding-left: 15px;
	}
	@media (max-width: 991px) {
		.center-sm {
			text-align: center;
		}
		.justify-sm {
			text-align: justify;
			hyphens: auto;
		}
	}
</style>